from django.urls import path

from .views import (
    AcceptLoadAPIView,
    AdminStatsAPIView,
    CreateLoadAPIView,
    CompleteLoadAPIView,
    CurrentDriverLoadsAPIView,
    DriverPostAvailabilityAPIView,
    DriverRequestsAPIView,
    DriverDashboardAPIView,
    DriverSMERequestsAPIView,
    DriverTraderRequestsAPIView,
    ForgotPasswordAPIView,
    InvoiceDetailAPIView,
    LoginAPI,
    PendingLoadsAPIView,
    PickupLoadAPIView,
    RegisterAPI,
    ResetPasswordAPIView,
    RespondPrePendingLoadAPIView,
    CreateSMERepeatOrderAPIView,
    SMEBulkBookingAPIView,
    SMEBulkBookingAutoAssignAPIView,
    SMEDashboardAPIView,
    SMEInvoicePDFAPIView,
    SMEInvoicesAPIView,
    SMERepeatOrdersAPIView,
    SMESchedulePickupAPIView,
    SMEShipmentsAPIView,
    SyncDriverPickedLoadsLocationAPIView,
    TrackShipmentAPIView,
    TruckListAPIView,
    UpdateDriverLocationAPIView,
    UserLoadsAPIView,
    UserLoadStatsAPIView,
    UserProfileAPIView,
    UserStatsAPIView,
    UserUpdateAPIView,
)

urlpatterns = [

    path("register/", RegisterAPI.as_view(), name="register"),
    path("login/", LoginAPI.as_view(), name="login"),
    path("forgot-password/", ForgotPasswordAPIView.as_view(), name="forgot-password"),
    path("reset-password/", ResetPasswordAPIView.as_view(), name="reset-password"),
    path("admin/stats/", AdminStatsAPIView.as_view(), name="admin-stats"),
    path('create-load/', CreateLoadAPIView.as_view(), name='create-load'),
    path("user/stats", UserStatsAPIView.as_view(), name="user-stats"),
    path("user/loads/stats", UserLoadStatsAPIView.as_view(), name="user-load-stats"),
    path("user/loads", UserLoadsAPIView.as_view(), name="user-loads"),
    path("user/profile", UserProfileAPIView.as_view(), name="user-profile"),
    path("user/update", UserUpdateAPIView.as_view(), name="user-update"),
    path("trucks", TruckListAPIView.as_view(), name="truck-list"),
    path("loads/pending", PendingLoadsAPIView.as_view(), name="pending-loads"),
    path("driver/requests/trader/", DriverTraderRequestsAPIView.as_view(), name="driver-requests-trader"),
    path("driver/requests/sme/", DriverSMERequestsAPIView.as_view(), name="driver-requests-sme"),
    path("driver/requests/", DriverRequestsAPIView.as_view(), name="driver-requests-all"),
    path("driver/dashboard/", DriverDashboardAPIView.as_view(), name="driver-dashboard"),
    path("loads/current", CurrentDriverLoadsAPIView.as_view(), name="current-driver-loads"),
    path("loads/<int:load_id>/accept", AcceptLoadAPIView.as_view(), name="accept-load"),
    path("loads/<int:load_id>/pickup", PickupLoadAPIView.as_view(), name="pickup-load"),
    path("loads/<int:load_id>/complete", CompleteLoadAPIView.as_view(), name="complete-load"),
    path("loads/<int:load_id>/pre-pending/respond", RespondPrePendingLoadAPIView.as_view(), name="respond-pre-pending-load"),
    path("loads/<int:load_id>/location", UpdateDriverLocationAPIView.as_view(), name="update-driver-location"),
    path("driver/location-sync", SyncDriverPickedLoadsLocationAPIView.as_view(), name="driver-location-sync"),
    path("driver/post-availability", DriverPostAvailabilityAPIView.as_view(), name="driver-post-availability"),
    path("track/<int:load_id>/", TrackShipmentAPIView.as_view(), name="track-shipment"),
    path("sme/dashboard/", SMEDashboardAPIView.as_view(), name="sme-dashboard"),
    path("sme/shipments/", SMEShipmentsAPIView.as_view(), name="sme-shipments"),
    path("sme/invoices/", SMEInvoicesAPIView.as_view(), name="sme-invoices"),
    path("invoice/<int:id>/", InvoiceDetailAPIView.as_view(), name="invoice-detail"),
    path("sme/invoices/<int:id>/pdf/", SMEInvoicePDFAPIView.as_view(), name="sme-invoice-pdf"),
    path("sme/repeat-orders/", SMERepeatOrdersAPIView.as_view(), name="sme-repeat-orders"),
    path("sme/repeat-orders/<int:id>/create/", CreateSMERepeatOrderAPIView.as_view(), name="sme-repeat-orders-create"),
    path("sme/schedule/", SMESchedulePickupAPIView.as_view(), name="sme-schedule"),
    path("sme/bulk-booking/", SMEBulkBookingAPIView.as_view(), name="sme-bulk-booking"),
    path("sme/bulk-booking/<int:id>/auto-assign/", SMEBulkBookingAutoAssignAPIView.as_view(), name="sme-bulk-booking-auto-assign"),

]
