# Generated by Django 5.2.10 on 2026-03-14 08:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('trader', 'Trader'), ('driver', 'Driver'), ('sme', 'SME / Business')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('ntn', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_from', models.CharField(max_length=100)),
                ('route_to', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_time', models.TimeField()),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=100)),
                ('drop_location', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_type', models.CharField(choices=[('Fragile', 'Fragile'), ('Normal', 'Normal')], max_length=10)),
                ('load_mode', models.CharField(choices=[('Full', 'Full Load'), ('Partial', 'Partial Load')], max_length=10)),
                ('budget_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_time', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('booking_id', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_invoices', to=settings.AUTH_USER_MODEL)),
                ('sme', models.ForeignKey(limit_choices_to={'role': 'sme'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadify_api.load')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('driver_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadify_api.driveravailability')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadify_api.load')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(choices=[('Shehzore', 'Shehzore'), ('Mazda', 'Mazda'), ('10-wheeler', '10-wheeler')], max_length=20)),
                ('registration_no', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=10)),
                ('total_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cnid', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
