# Generated by Django 5.2.10 on 2026-03-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadify_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='cnid',
            new_name='cnic',
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver_availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='loadify_api.driveravailability'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='loadify_api.load'),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sme',
            field=models.ForeignKey(limit_choices_to={'role': 'sme'}, on_delete=django.db.models.deletion.CASCADE, related_name='sme_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL),
        ),
    ]
