# Generated by Django 5.2.10 on 2026-03-15 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadify_api', '0002_rename_cnid_truck_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='loadify_api.driveravailability'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='loadify_api.load'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='available_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='available_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='current_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='route_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='route_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='total_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='booking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loadify_api.load'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sme',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sme'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='load',
            name='budget_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='drop_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_mode',
            field=models.CharField(blank=True, choices=[('Full', 'Full Load'), ('Partial', 'Partial Load')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_type',
            field=models.CharField(blank=True, choices=[('Fragile', 'Fragile'), ('Normal', 'Normal')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='available_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='cnic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='total_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(blank=True, choices=[('Shehzore', 'Shehzore'), ('Mazda', 'Mazda'), ('10-wheeler', '10-wheeler')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('trader', 'Trader'), ('driver', 'Driver'), ('sme', 'SME / Business')], max_length=10, null=True),
        ),
    ]
