# Generated by Django 5.2.10 on 2026-03-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadify_api', '0003_alter_booking_booked_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='cnic',
            new_name='cnid',
        ),
    ]
