# Generated by Django 5.2.10 on 2026-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadify_api', '0016_increase_decimal_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpickup',
            name='calculated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledpickup',
            name='final_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledpickup',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
